[general]
live_config_reload = true
import = ["~./colors/matugen.toml"]

[font]
size = 10

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

# Bold = Nothing Dot-Matrix – für Prompts, Überschriften etc.
# [font.bold]
# family = "NDOT 47 (inspired by NOTHING)"
# style = "Regular"

# Optional: falls du italic brauchst, sonst weglassen
[font.bold_italic]
family = "NDOT 47 (inspired by NOTHING)"
style = "Regular"


[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9
dynamic_title = true
decorations = "none"

[window.padding]
x = 18
y = 20

[cursor]
blink_interval = 450
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

# [colors.cursor]
# cursor = "0xffffff"
# text = "0x0f0f0f"
#
# [colors.primary]
# background = "#0f0f0f"
# foreground = "#f2f2f2"        # leicht angepasst, matcht eher Nothing/Waybar

# [colors.selection]
# background = "0xffffff"
# text = "0x0f0f0f"

# Monochrom-ish + Orange-Akzent
# [colors.normal]
# black   = "#151515"
# red     = "#ff6a00"  # Orange Akzent (statt knallrot)
# green   = "#bfbfbf"
# yellow  = "#ffb366"  # softer Orange-Ton
# blue    = "#d0d0d0"
# magenta = "#c8c8c8"
# cyan    = "#d8d8d8"
# white   = "#e5e5e5"
#
# [colors.bright]
# black   = "#3a3a3a"
# red     = "#ff8a33"  # heller Orange-Ton
# green   = "#e0e0e0"
# yellow  = "#ffd199"
# blue    = "#f0f0f0"
# magenta = "#fafafa"
# cyan    = "#ffffff"
# white   = "#ffffff"
#
